# Use a base image
FROM python:3.10

# Set the working directory
WORKDIR /app  

# Copy the requirements file into the container
COPY requirements.txt . 

# Install required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Command to run the application
CMD ["python", "sensor_mqtt.py"]